### ISSUE TITLE
Supermetrics Rightsize - Potential CPU Usage Reclaimable (GHz)

### ISSUE THREAD

**Issue by ame92** [notoriousbdg/vrops-dashboard-rightsizing_details#1]
Hello,
I not understand why this supermetrics (Rightsize - Potential CPU Usage Reclaimable (GHz)) is 0, and on wich view is used?

**Comment by notoriousbdg** [comment]
That's intentional to reinforce the fact that reclaiming vCPUs from an oversized VM does not reclaim any GHz of CPU capacity when using the demand model.  I have a more detailed explanation on https://blogs.vmware.com/management/2020/01/rightsizing-vms-with-vrealize-operations.html that might be of interest to you.

**Comment by ame92** [comment]
ok perfect thank you very much
